/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/ui/ActionButton.vue')['default']
    CardSection: typeof import('./src/components/ui/CardSection.vue')['default']
    Form: typeof import('./src/components/forms/Form.vue')['default']
    InputNumber: typeof import('./src/components/ui/InputNumber.vue')['default']
    InputText: typeof import('./src/components/ui/InputText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleButton: typeof import('./src/components/ui/ToggleButton.vue')['default']
  }
}
